sudo: required


services:
    - docker
    
before_install:
    - docker build -t mun-creative/docker-startup -f Dockerfile.dev .
    
    
script:
    - docker run mun-creative/docker-startup npm run test -- --coverage  --watchAll=false
    

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker_startup"
    env: "DockerStartup-env"
    bucket_name: "elasticbeanstalk-us-east-1-674559593594"
    bucket_path: "docker_startup"
    on:
        branch: master
        
        
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
        
        

