sudo: required


services:
    - docker
    
before_install:
    - docker build -t mun-creative/docker-startup -f Dockerfile.dev .
    
    
script:
    - docker run mun-creative/docker-startup npm run test -- --coverage